controller_list:
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    publish_rate: 50

  - name: joint1_position_controller
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint2_position_controller
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint3_position_controller
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint4_position_controller
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint5_position_controller
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint6_position_controller
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint7_position_controller
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint8_position_controller
    type: effort_controllers/JointPositionController
    joint: joint8
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint9_position_controller
    type: effort_controllers/JointPositionController
    joint: joint9
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint10_position_controller
    type: effort_controllers/JointPositionController
    joint: joint10
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint11_position_controller
    type: effort_controllers/JointPositionController
    joint: joint11
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint12_position_controller
    type: effort_controllers/JointPositionController
    joint: joint12
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint13_position_controller
    type: effort_controllers/JointPositionController
    joint: joint13
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint14_position_controller
    type: effort_controllers/JointPositionController
    joint: joint14
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint15_position_controller
    type: effort_controllers/JointPositionController
    joint: joint15
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint16_position_controller
    type: effort_controllers/JointPositionController
    joint: joint16
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint17_position_controller
    type: effort_controllers/JointPositionController
    joint: joint17
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint18_position_controller
    type: effort_controllers/JointPositionController
    joint: joint18
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint19_position_controller
    type: effort_controllers/JointPositionController
    joint: joint19
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint20_position_controller
    type: effort_controllers/JointPositionController
    joint: joint20
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint21_position_controller
    type: effort_controllers/JointPositionController
    joint: joint21
    pid: {p: 100.0, i: 0.01, d: 1.0}

  - name: joint22_position_controller
    type: effort_controllers/JointPositionController
    joint: joint22
    pid: {p: 100.0, i: 0.01, d: 1.0}

x7s_front_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_front_left_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

x7s_front_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_front_right_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

x7s_back_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_back_left_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

x7s_back_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_back_right_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
  
x7s_base_controller:
  type: effort_controllers/JointGroupVelocityController
  joints:
    - wheel_front_left_joint
    - wheel_front_right_joint
    - wheel_back_left_joint
    - wheel_back_right_joint
    
x7s_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
      
  # Base frame_id
  base_frame_id: base_link

  # Odom frame id
  odom_frame_id: odom

  enable_odom_tf: false
  
twist_mux:
  topics:
  - name    : Joystick
    topic   : teleop/cmd_vel
    timeout : 0.5
    priority: 100

  - name    : Navigation
    topic   : move_base/cmd_vel
    timeout : 0.5
    priority: 50

  - name    : Docking
    topic   : dock/cmd_vel
    timeout : 0.5
    priority: 20

  - name    : External
    topic   : cmd_vel
    timeout : 0.5
    priority: 10

ekf_localization_node:
  frequency: 50
  sensor_timeout: 0.1

  two_d_mode: true
  publish_tf: true
  publish_acceleration: false
  print_diagnostics: false
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
